Task 2 and 5/code-test/routes/web.php
<?php

use App\Http\Controllers\MemberController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SchoolController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('task2');
});

Route::get('/search-profiles',[ProfileController::class,'search'])->name('profile.search');
Route::resource('members',MemberController::class);

Route::get('schools',[SchoolController::class,'searchBySchool'])->name('school.search');
Route::post('school/members',[SchoolController::class,'members'])->name('school.members');
Route::get('member/export/{school_id}',[SchoolController::class,'export'])->name('school.members.export');

Task 2 and 5/code-test/app/Models/Email.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Email extends Model
{
    use HasFactory;
}

Task 2 and 5/code-test/app/Models/Member.php
<?php

namespace App\Models;

use App\Models\School;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Member extends Model
{
    use HasFactory;

    protected $table = 'members';

    protected $fillable = ['name','email'];

    protected $appends = ['school_name'];

    public function schools(){
        return $this->belongsToMany(School::class,'member_has_schools','member_id','school_id');
    }

    public function getSchoolNameAttribute(){
        return implode(', ',$this->schools()->pluck('school_name')->toArray());
    }
    
}

Task 2 and 5/code-test/app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;

    protected $table = 'profiles';

    public function email(){
        return $this->belongsTo(Email::class,'userRefID','userRefID');
    }
}

Task 2 and 5/code-test/app/Models/School.php
<?php

namespace App\Models;

use App\Models\Member;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class School extends Model
{
    use HasFactory;

    public function members(){
        return $this->belongsToMany(Member::class,'member_has_schools','school_id','member_id');
    }
}

Task 2 and 5/code-test/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Task 2 and 5/code-test/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Task 2 and 5/code-test/app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Repository\MemberRepository;
use App\Http\Repository\SchoolRepository;

class MemberController extends Controller
{
    private $school;
    private $repo;

    public function __construct(SchoolRepository $school, MemberRepository $member)
    {
        $this->school = $school;
        $this->repo = $member;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schools = $this->school->get();

        return view('task5',compact('schools'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $memeber = $this->repo->store($request);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Task 2 and 5/code-test/app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Repository\ProfileRepository;
use App\Http\Resources\ProfileResource;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    private $repo;

    public function __construct(ProfileRepository $repo){
        $this->repo = $repo;
    }
    
    public function search(Request $request){
        if(is_null($request->name)){
            return;
        }
        
        $result = $this->repo->search($request->name);
        
        return ProfileResource::collection($result);
    }
}

Task 2 and 5/code-test/app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use App\Exports\MembersExport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Repository\SchoolRepository;

class SchoolController extends Controller
{
    private $repo;

    public function __construct(SchoolRepository $repo){
        $this->repo = $repo;
    }

    public function searchBySchool(){
        $schools = $this->repo->get();
        return view('school-search',compact('schools'));
    }

    public function members(Request $request){
        if(!isset($request->school)){
            return redirect()->back();
        }

        $members = $this->repo->membersBySchool($request->school);
        $data = array(
            'members' => $members,
            'school_id' => $request->school
        );
        return view('school-members',$data);

    }

    public function export($school_id){
        $members = $this->repo->membersBySchool($school_id);
        
        $export = new MembersExport($members);
        return Excel::download($export, 'members.csv');
    }

        
}

Task 2 and 5/code-test/resources/views/exports/members.blade.php
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Associated Schools</th>
    </tr>
    </thead>
    <tbody>
    @foreach($members as $member)
        <tr>
            <td>{{ $member->name }}</td>
            <td>{{ $member->email }}</td>
            <td>{{ $member->school_name }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

Task 2 and 5/code-test/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title', 'Code Test')</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Code Test</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Task 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('members.index')}}">Task 5</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('school.search')}}">Search By School</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        @yield('content')
    </div>
    <!-- Include Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    @stack('script')
    
</body>
</html>

Task 2 and 5/code-test/resources/views/school-members.blade.php
@extends('layouts.app')

@section('title', 'School Search')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="offset-md-10 col-2">
            <button type="button" class='btn btn-sm btn-success' id='export'>Export to CSV</button>
        </div>
    </div>
    <h1>School Members</h1>
    <table class='table table-stripped'>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($members as $member)
                <tr>
                    <td>
                        {{$member->name}}
                    </td>
                    <td>
                        {{$member->email}}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
</div>
@endsection

@push('script')
    <script>
        $(document).ready(function() {
            $('#export').on('click',function(){
                window.location.href = "{{route('school.members.export',$school_id)}}";
            });
        });
    </script>
@endpush

Task 2 and 5/code-test/resources/views/school-search.blade.php
@extends('layouts.app')

@section('title', 'School Search')

@section('content')
<div class="container mt-5">
    <h1>Search Members</h1>
    <div class="row">
        <form action="{{route('school.members')}}" method="POST" class="form" id="searchForm" enctype="multipart/form-data">
            @csrf
            <div class="col-md-12">
                <div class="form-group">
                    <label for="school">School</label>
                    <select id="school" name="school" class="form-control" id='multiselect'>
                        <option value="" disabled selected>Select schools</option>
                        @foreach ($schools as $id => $name)
                            <option value="{{$id}}">{{$name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-sm ml-2">Search</button>
        </form>
    </div>
    
</div>
@endsection

@push('script')
<script>
    
</script>
    
@endpush

Task 2 and 5/code-test/resources/views/task2.blade.php
@extends('layouts.app')

@section('title', 'Task 2')

@section('content')
<div class="container mt-5">
    <h1>Search Profiles</h1>
    <form action="javascript:void(0)" class="form-inline" id="searchForm" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" name="name" class="form-control form-control-sm" placeholder="Name">
        </div>
        <button type="submit" class="btn btn-primary btn-sm ml-2">Search</button>
    </form>

    <table class="table" id='profileTable'>
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
            </tr>
        </thead>
        
        <tbody>

        </tbody>
    </table>
    
</div>
@endsection

@push('script')
<script>
    $(document).ready(function(){
        $('form').submit(function(){
            $.ajax({
                url: "{{route('profile.search')}}",
                type: 'GET',
                data: {
                    name: $("input[name='name']").val()
                },
                success: function({data}) {
                    let html = '';
                    $('#profileTable').find('tbody').html('');

                    if(!data){
                        html += `
                            <tr>
                                <td colspan='3' class='text-center'>No Records Found</td>
                            </tr>
                        `;

                        $('#profileTable').find('tbody').append(html);
                        return;
                    }

                    Object.values(data).forEach(profile => {
                        html += `
                            <tr>
                                <td>${profile.firstName}</td>
                                <td>${profile.lastName}</td>
                                <td>${profile.email}</td>
                            </tr>
                        `;
                    });

                    $('#profileTable').find('tbody').append(html);
                }
            });
        });
    });
</script>
    
@endpush

Task 2 and 5/code-test/resources/views/task5.blade.php
@extends('layouts.app')

@section('title', 'Task 5')

@section('content')
<div class="container mt-5">
    <h1>Registration Form</h1>
    <form method="POST" action="{{ route('members.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name" class="form-control">
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" class="form-control">
                </div>
            </div>
        </div>        

        <div class="form-group">
            <label for="school">School</label>
            <select id="school" name="schools[]" class="form-control" id='multiselect' multiple>
                <option value="" disabled selected>Select schools</option>
                @foreach ($schools as $id => $name)
                    <option value="{{$id}}">{{$name}}</option>
                @endforeach
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection